### ISSUE TITLE
postcss-image-set-polyfill

### ISSUE THREAD

**Issue by RyanZim** [jonathantneal/postcss-preset-env#12]
https://github.com/SuperOl3g/postcss-image-set-polyfill has its dependencies pinned: https://github.com/SuperOl3g/postcss-image-set-polyfill/blob/master/package.json#L22

This results in postcss being downloaded twice; which is poor for disk space and perf in Node, and is a real problem in the browser for the REPL. I've currently hacked around this to force a single instance of postcss, but it'd be nice if this was fixed at the root of the problem. Shall I open a PR there unpinning postcss?

**Comment by jonathantneal** [comment]
Yes, I think we should update that plugin.

**Comment by RyanZim** [comment]
Done: https://github.com/SuperOl3g/postcss-image-set-polyfill/pull/23

**Comment by jonathantneal** [comment]
Okay, I’ve made the fix on my own branch, but while I was in there I noticed a few other issues, namely that declaration ordering was totally lost because it used `decl.root().append`.

So, I started this work on a fork, and I’m unsure if I should just PR that and then publish a fork while we wait?

https://github.com/jonathantneal/postcss-image-set-polyfill/tree/npm/jonathantneal

**Comment by RyanZim** [comment]
It's up to you, honestly.
